
# baseURL = "https://example.com"
# title   = "Max Robinson"
# languageCode = "en-us"
# theme = "academia-hugo"

# PygmentsCodeFences = true
# PygmentsStyle = "monokai"

# paginate  = 10
# rssLimit  = 10  # Maximum number of items in the RSS feed.
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

# archetypeDir = "archetypes"
# contentDir   = "content"
# dataDir      = "data"
# layoutDir    = "layouts"
# publishDir   = "public"

# buildDrafts  = false
# buildFuture  = false
# buildExpired = false
# canonifyURLs = true

# enableRobotsTXT = true
# enableGitInfo   = false
# enableEmoji     = true
# enableMissingTranslationPlaceholders = false
# disableRSS     = false
# disableSitemap = false
# disable404     = false
# disableHugoGeneratorInject = false

# [permalinks]
#   posts = "/posts/:year/:month/:title/"

# [author]
#   name = "Max Robinson"

# # [blackfriday]
# #   hrefTargetBlank = true

# [taxonomies]
#     category = "blog"
#     tag      = "tags"
#     series   = "series"

# [params]
#   dateform        = "Jan 2, 2006"
#   dateformShort   = "Jan 2"
#   dateformNum     = "2006-01-02"
#   dateformNumTime = "2006-01-02 15:04"

#   # Metadata mostly used in document's head
#   # 
#   description = "Max Robinson"
#   keywords = ""
#   images = [""]

#   # Home subtitle of the index page.
#   #
#   homeSubtitle = ""

#   # Set a background for the homepage
#   # backgroundImage = "assets/images/image.jpg"
#   # backgroundImage = "static/img/image.jpg"

#   # Prefix of link to the git commit detail page. GitInfo must be enabled.
#   #
#   # gitUrl = ""f

#   # Set disableReadOtherPosts to true in order to hide the links to other posts.
#   #
#   disableReadOtherPosts = false

#   # Enable theme toggle
#   # 
#   # This options enables the theme toggle for the theme. 
#   # Per default, this option is off. 
#   # The theme is respecting the prefers-color-scheme of the operating systeme. 
#   # With this option on, the page user is able to set the scheme he wants. 
#   enableThemeToggle = true

#   # Sharing buttons
#   #
#   # There are a lot of buttons preconfigured. If you want to change them,
#   # generate the buttons here: https://sharingbuttons.io
#   # and add them into your own `layouts/partials/sharing-buttons.html`
#   #
#   enableSharingButtons = true

#   # Global language menu
#   #
#   # Enables the global language menu.
#   #
#   enableGlobalLanguageMenu = true

#   # Integrate Javascript files or stylesheets by adding the url to the external assets or by
#   # linking local files with their path relative to the static folder, e.g. "css/styles.css"
#   #
#   customCSS = []
#   customJS  = []

#   # Toggle this option need to rebuild SCSS, requires extended version of Hugo
#   #
#   justifyContent = false  # Set "text-align: justify" to .post-content.

#   # Custom footer 
#   # If you want, you can easily override the default footer with your own content. 
#   #
#   [params.footer]
#     trademark = true
#     rss = false
#     copyright = false
#     author = true

#     topText = []
#     bottomText = []

#   # Colors for favicons
#   #
#   [params.favicon.color]
#     mask = "#1b1c1d"
#     msapplication = "#1b1c1d"
#     theme = "#1b1c1d"

#   [params.logo]
#     logoMark     = "$"
#     logoText     = "cd /home/"
#     logoHomeLink = "/"
#     # Set true to remove the logo cursor entirely.
#     logoCursorDisabled = true
#     # Set to a valid CSS color to change the cursor in the logo.
#     # logoCursorColor    = "#67a2c9"
#     # Set to a valid CSS time value to change the animation duration, "0s" to disable.
#     # logoCursorAnimate  = "2s"

#   # Commento is more than just a comments widget you can embed — 
#   # it’s a return to the roots of the internet. 
#   # An internet without the tracking and invasions of privacy. 
#   # An internet that is simple and lightweight. 
#   # An internet that is focused on interesting discussions, not ads. 
#   # A better internet.
#   # Uncomment this to enable Commento.
#   #
#   # [params.commento]
#   #   url = ""

#   # Uncomment this if you want a portrait on your start page
#   #
#   [params.portrait]
#     path     = "/img/snow_crop_github.jpg"
#     alt      = "Portrait"
#     maxWidth = "200px"

#   # Social icons
#   # [[params.social]]
#   #   name = "twitter"
#   #   url  = "https://twitter.com/"

#   [[params.social]]
#     name = "email"
#     url  = "mailto:maxrobinsoncs@gmail.com"

#   [[params.social]]
#     name = "github"
#     url  = "https://github.com/MaxRobinson"

#   [[params.social]]
#     name = "linkedin"
#     url  = "https://www.linkedin.com/in/maxrobinson31415"

#   # [[params.social]]
#   #   name = "stackoverflow"
#   #   url  = "https://www.stackoverflow.com/"

# [languages]
#   [languages.en]
#     subtitle  = ""
#     weight    = 1
#     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "about/"
#   [[menu.main]]
#     identifier = "posts"
#     name       = "Posts"
#     url        = "/posts"


# ---------------------------------------

# Configuration of Academia
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Max Robinson"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://example.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "Copyright &copy; {year}"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

favicon = "snow_crop_github.jpg"

############################
## Advanced options below ##
############################

# Name of Academia theme folder in `themes/`.
theme = "academia-hugo"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687


# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.
color_theme = "default"


paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

# [imaging]
#   resampleFilter = "lanczos"
#   quality = 90
#   anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
